image:
- Previous Ubuntu
- Visual Studio 2015

install:
- ps: >-
    .\CI\02_Install.ps1
build_script:
- ps: >-
    write-host "Skipping build"
test_script:
- ps: >-
    .\CI\04_Tests.ps1

skip_commits:
  files:
    - docs/*
    - README.MD
    - mkdocs.yml

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
